name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 */6 * * *"

jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      DB_CONN_STR: ${{ vars.DB_CONN_STR }}
      DB_USERNAME: ${{ vars.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rspec test/integration